baseurl = "http://www.example.com"
title = "Agility"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Agility"
  info = "Frontend Developer"
  avatarurl = "/images/avatar.jpg"
  # gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2020

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-1x"
  weight = 1
  url = "https://github.com/Agility6/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-1x"
  weight = 2
  url = "https://twitter.com/Tang86d/"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"